### ISSUE TITLE
Duplicate events?

### ISSUE THREAD

**Issue by ryanio** [segment-integrations/analytics-ios-integration-amplitude#1]
It looks like I'm getting duplicate events through both the included Ampltiude integration (lib: iOS) Segment (lib: analytics-ios):

![screen shot 2015-12-11 at 10 24 52 am](https://cloud.githubusercontent.com/assets/22116/11751918/873e39e2-9ff1-11e5-9582-2b0f0c81dfb3.png)

Any idea what could be going on?

**Comment by f2prateek** [comment]
Which version of the iOS SDK are you using? There was a bug in an older release that has since been fixed.
