### ISSUE TITLE
Can we make this a Swift Package?

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-ios-integration-amplitude#106]
I'm trying to move my project away from Cocoapods, and almost all of my libraries have corresponding Swift Packages.

It would be great if this were available as a Swift Package so I could remove Cocoapods from my machine, and stop using it altogether.

**Comment by bsneed** [comment]
Hi @skydivedan,

You'd probably be interested in our new Analytics-Swift library here: https://github.com/segmentio/analytics-swift

There's an amplitude session plugin that makes it such that you don't even need the Amplitude SDK to be linked and it can all be done via cloud mode.

**Comment by skydivedan** [comment]
Thanks, @bsneed, this looks interesting / promising.

However, I'm going to refrain from jumping to the "new hotness" at the moment, for the following reasons:
- I also use Appboy/Braze. There isn't an integration for that yet, and I'd rather not have two versions of Segment (the old, and the new Swift one) installed in my project.
- All of the integrations are listed in the "Examples" folder... which makes it appear that these aren't actually supported "for realz". I mean, I understand that they probably work, but it seems a little odd to pull in code that's part of an example project.

That said, this stuff does look totally promising, and I'm looking forward to using it once it matures more.
