### ISSUE TITLE
GZip Extension Conflict

### ISSUE THREAD

**Issue by dcvz** [segment-integrations/analytics-ios-integration-amplitude#15]
There used to be a conflict what the recently introduced Gzip extension in `analytics-ios`. That was just recently fixed. Could this library be updated to have as a dependency a version of `analytics-iso` that has the namespaces GZIP extension?

Thanks!

**Comment by f2prateek** [comment]
Integrations will generally pull in the latest version of the Analytics pod if you don't have a version for `pod Analytics` explicitly declared. You'll probably need to run pod update to pull in the latest version.

https://github.com/segment-integrations/analytics-ios-integration-amplitude/blob/master/Segment-Amplitude.podspec#L24. This one specifically works with  any version > 3.2.

If this is the specific fix you are talking about, https://github.com/segmentio/analytics-ios/pull/588/commits/34b7269b189a7c624571b70162eb9bb1c25fdbd9 then it is not released yet. It will be in the next release. You can use the `master` branch for now.
