### ISSUE TITLE
Main thread API violations

### ISSUE THREAD

**Issue by danielgalasko** [segment-integrations/analytics-ios-integration-amplitude#28]
Hi, 

We are currently experiencing main thread API asserts for this integration that prevent us from running tests on our CI. It also throws these asserts while developing.

The issue begins in `SEGAmplitudeIntegration` that calls `[[Amplitude instance] initializeApiKey:apiKey];` 

This call should be called on a main queue OR prompt Amplitude to update their SDK to do this. I am linking [Amplitude](https://github.com/amplitude/Amplitude-iOS/issues/147) for this one.

It all boils down to how Amplitude uses UIApplication:

```
        UIApplication *app = [self getSharedApplication];
        if (app != nil) {
            UIApplicationState state = app.applicationState;
            if (state != UIApplicationStateBackground) {
                // If this is called while the app is running in the background, for example
                // via a push notification, don't call enterForeground
                [self enterForeground];
            }
        }
```

So either Segment fixes this or Amplitude but it would be nice to see this resolved. Happy to submit a patch PR

<img width="1418" alt="screen shot 2017-10-11 at 4 53 55 pm" src="https://user-images.githubusercontent.com/4479146/31448936-ebd22e58-aea5-11e7-9d24-17734506d793.png">

**Comment by danielgalasko** [comment]
In the meanwhile I have submitted https://github.com/amplitude/Amplitude-iOS/pull/148 to address this I am just not sure which one will be done first.

The article that outlines the issue this causes in hanging the simulator is discussed [here](http://shashikantjagtap.net/main-thread-checker-xcuitests-xcode-9/)

**Comment by ladanazita** [comment]
Thanks for raising this @danielgalasko ! Looks like @djih merged those changes - closing.

**Comment by djih** [comment]
@ladanazita I love how the updates are automatically pulled into the Segment integration
