### ISSUE TITLE
compilation fail

### ISSUE THREAD

**Issue by neywen** [segment-integrations/analytics-ios-integration-amplitude#3]
Hello,
In my current iOS project, I've added the cocoapod Segment-Amplitude, last available version 3.2.0-alpha, with the cocoapod Analytics 3.0.6.

The compilation fails in AMPDatabaseHelper.m, with "use of undeclared identifier SQLITE_OPEN_READWRITE".

I'm still looking for way to fix that, but if anyone has an idea, I'm interested !
Thanks
l.

**Comment by smeador** [comment]
I'm having the same compilation issue. It seems like this integration is not very well supported.

Please advise.

**Comment by f2prateek** [comment]
Try 1.1.0

**Comment by f2prateek** [comment]
(you're using a really old alpha release which is the issue)
