### ISSUE TITLE
Segment-Amplitude build fails

### ISSUE THREAD

**Issue by andrewloyola** [segment-integrations/analytics-ios-integration-amplitude#7]
i tried adding this Segment-Amplitude as a dependency to my podfile, similarly to the Segment-Mixpanel and Segment-Branch integrations that we also use.  However, it fails building, Segment-Amplitude, since it can't find a the Amplitude.h header.  Is this a known issue?

FWIW, Adding Amplitude-iOS seperately from segment's wrapper pod works, but we don't get the segment benefits that way obviously.

Also, I was looking at the example project for any tips, but it doesn't seem to actually implement the Amplitude SDK, and is instead an empty integration. 

My build details:
Swift 2.2 project with Xcode 7.3
platform: ios 9.0 only 
use_frameworks! is enabled

**Comment by f2prateek** [comment]
Can you clarify where you're seeing that error? Which version are you using?

**Comment by andrewloyola** [comment]
<img width="783" alt="screenshot 2016-04-06 13 41 34" src="https://cloud.githubusercontent.com/assets/1688758/14326742/5a666f30-fbfd-11e5-9e43-9ab36e5b2a27.png">

see attached screenshot. 

Amplitude-iOS = 3.5.0
Segment-Amplitude 1.1.1

it looks like the latest podspec points to 3.6.0 of Amplitude-iOS? perhaps that's part of the issue. Any plans to push this out?

**Comment by f2prateek** [comment]
I just published 1.2.0, but unsure if that's going to fix this issue.

**Comment by hankim813** [comment]
@andrewloyola do you still have this issue after @f2prateek recent push?

**Comment by andrewloyola** [comment]
sorry for the delay, I just checked and it indeed does fail in the same way with 1.2.0. @hankim813 @f2prateek

**Comment by f2prateek** [comment]
@andrewloyola could you share your podfile (and Podfile.lock)?

**Comment by louoso** [comment]
Same issue for me. If you change `<Amplitude-iOS/Amplitude.h>` to `<Amplitude_iOS/Amplitude.h>` it resolves it.

**Comment by louoso** [comment]
So for frameworks "if your product name has any nonalphanumeric characters, such as a period (.), they are replaced with an underscore (_) in your product module name" from https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by f2prateek** [comment]
I see, so is this is because you have `use_frameworks!` in your Podfile?

**Comment by louoso** [comment]
yeah, pretty much

**Comment by f2prateek** [comment]
Is there anything we can do? Changing to `_` instead of `-` will fail for users not using `use_frameworks!`. I wonder if using module imports automatically does the right thing https://github.com/segment-integrations/analytics-ios-integration-amplitude/pull/5/files

**Comment by louoso** [comment]
I can't see how that wouldn't work for me, but I have no idea about anyone who isn't using `use_frameworks!`. Do you have a test project setup that way?

**Comment by louoso** [comment]
just to confirm, using module imports works for me.

**Comment by dcvz** [comment]
changing the import to `#import <Amplitude_iOS/Amplitude.h>` works

**Comment by andrewloyola** [comment]
fixed as of release 1.4.0

**Comment by f2prateek** [comment]
Thanks for confirming!
