### ISSUE TITLE
Carthage compile error

### ISSUE THREAD

**Issue by juaga** [segment-integrations/analytics-ios-integration-amplitude#77]
Hi,

I'm trying to add this Segment integration via Carthage but it fails with `Task failed with exit code 65`.  

Not sure if related but, I had to add it to the Cartfile using `git "https://github.com/segment-integrations/analytics-ios-integration-amplitude.git"` as I couldn't find the name to install it via Carthage.

The log error file contains this:

** ARCHIVE FAILED **

The following build commands failed:
CompileC /Users/juangarcia/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/analytics-ios-integration-amplitude/3.0.2/Build/Intermediates.noindex/ArchiveIntermediates/Segment-Amplitude/IntermediateBuildFilesPath/Segment-Amplitude.build/Release-iphoneos/Segment-Amplitude.build/Objects-normal/arm64/SEGAmplitudeIntegrationFactory.o /Users/juangarcia/Development/Name/Carthage/Checkouts/analytics-ios-integration-amplitude/Pod/Classes/SEGAmplitudeIntegrationFactory.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

CompileC /Users/juangarcia/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/analytics-ios-integration-amplitude/3.0.2/Build/Intermediates.noindex/ArchiveIntermediates/Segment-Amplitude/IntermediateBuildFilesPath/Segment-Amplitude.build/Release-iphoneos/Segment-Amplitude.build/Objects-normal/armv7/SEGAmplitudeIntegration.o /Users/juangarcia/Development/Name/Carthage/Checkouts/analytics-ios-integration-amplitude/Pod/Classes/SEGAmplitudeIntegration.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

CompileC /Users/juangarcia/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/analytics-ios-integration-amplitude/3.0.2/Build/Intermediates.noindex/ArchiveIntermediates/Segment-Amplitude/IntermediateBuildFilesPath/Segment-Amplitude.build/Release-iphoneos/Segment-Amplitude.build/Objects-normal/arm64/SEGAmplitudeIntegration.o /Users/juangarcia/Development/Name/Carthage/Checkouts/analytics-ios-integration-amplitude/Pod/Classes/SEGAmplitudeIntegration.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

CompileC /Users/juangarcia/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4.1_11E503a/analytics-ios-integration-amplitude/3.0.2/Build/Intermediates.noindex/ArchiveIntermediates/Segment-Amplitude/IntermediateBuildFilesPath/Segment-Amplitude.build/Release-iphoneos/Segment-Amplitude.build/Objects-normal/armv7/SEGAmplitudeIntegrationFactory.o /Users/juangarcia/Development/Name/Carthage/Checkouts/analytics-ios-integration-amplitude/Pod/Classes/SEGAmplitudeIntegrationFactory.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

(4 failures)
_____________

Thanks!

**Comment by bsneed** [comment]
I think this has been fixed as of 3.1.0.  If you see any problems after updating, please let me know.  🙇‍♂️
