### ISSUE TITLE
Breaking Changes in Amplitude 7.0.0 Dependency

### ISSUE THREAD

**Issue by jseetVICE** [segment-integrations/analytics-ios-integration-amplitude#82]
[Amplitude-iOS 7.0.0 Release Notes](https://github.com/amplitude/Amplitude-iOS/blob/master/CHANGELOG.md)

**Summary:** Amplitude removed a few things and now Segment-Amplitude is broken.

> 
> Background: Users reported that IDFA MACRO still do not prevent app rejections. So we make both idfa and location tracking to be fully customer driven.
> 
> Add `adSupportBlock` to let idfa tracking to be customer driven.
> Add `locationInfoBlock` to let location tracking to be customer driven.
> Remove `enableLocationListening`, `disableLocationListening` and `updateLocation` APIs.

**Comment by bsneed** [comment]
Fixed in 3.2.1

**Comment by yawaraym** [comment]
@bsneed What if people want to use 3.1.0.
as 3.2.1 using 4.x.x of analytics (segments) which is a pre-release.

**Comment by bsneed** [comment]
@yawaraym The dependency is unpinned.  If you specify a specific version in your app's podfile, it should still work fine.  If not, you'll need to fork and make any changes for the time being.
